### ISSUE TITLE
Amazing plugin idea but sidebar not showing

### ISSUE THREAD

**Issue by jasonnoahchoi** [marcosvidal/Sketch-Notebook#26] opened 2014-12-27 01:04 UTC
From the screenshots, it looks really useful. I'm wondering if you ever encountered something like this:

http://i.imgur.com/xfsRi1E.png

If I click Add Comments, the additional page gets added. Afterwards, I try clicking Add Comments again but nothing really happens so I tried to toggle sidebar visibility and then the above image happens. Doesn't seem right. Any ideas would be appreciated! Thanks!

**Comment by marcosvidal** [comment] 2015-01-07 12:15
Hey @jasonnoahchoi , sorry for the late answer, I've been out for xmas break. 

Does this still happen to you? It looks like an upgrade issue, like @thewebyak has already told you... If it's still happening, could you please use http://quickcast.io/ or something similar to explain the behaviour?

**Comment by jasonnoahchoi** [comment] 2015-01-09 04:45
Hey @marcosvidal thanks for getting back to me.

Yes, it still does for some reason. I'm not exactly sure why. It seems other sketch plugins work okay. 

Here's a video link of what is happening: http://quick.as/oww5tlrg

**Comment by jasonnoahchoi** [comment] 2015-01-15 12:07
@marcosvidal I wanted to let you know that once I upgraded to 3.2.2, it works fine!

**Comment by marcosvidal** [comment] 2015-01-15 12:24
Glad to hear that!!

I'm closing this issue since it looks like a duplicate of https://github.com/marcosvidal/Sketch-Notebook/issues/17

**Closed by marcosvidal** 2015-01-15 12:24 UTC

**Comment by lequera14** [comment] 2015-05-13 07:39
Hi marcos,

I am not getting the dark side bar when I chose add comments after selecting a group / layer. same issue reported by Jason.
